### ISSUE TITLE
3 warnings in this pod when using the latest XCode

### ISSUE THREAD

**Issue by jonasman** [trustedshops/trustbadge_iOS#49] opened 2017-01-17 15:49 UTC
There are 3 warnings when using the latest XCode

They are all in the init.
`Conflicting nullability specifier on return types, 'nullable' conflicts with existing specifier 'nonnull'`

TRSOrder.h
TRSProduct.h
TRSProductReview.h

**Comment by GeroHerkenrath** [comment] 2017-01-17 16:02
Thank you for letting me know. I will fix this asap.

**Comment by GeroHerkenrath** [comment] 2017-01-19 10:02
I can't reproduce these warnings, neither in the Example project of the pod nor in a completely fresh test project. I don't see any conflicting nullability specifiers in the header files either. By looking at it, I mean.

Is it possible a `pod update` somehow messed up your project? Please note that as of 0.8.0 nullability specifiers changed, since now the email is optional when processing an order. I have no idea why you would see any conflicts in the `TRSProductReview.h` file though, as that wasn't directly affected by this change.

If you still see the warning even in a test project that uses the 0.8.0 version of the pod please let me know. Maybe you could then share an example project where that happens.

Should it be an issue with the pod itself I apologize for any inconvenience. You can be assured that these warnings should not lead to problems in your app as long as you are using the affected methods according to the documentation. A missing email simply results in the checkout process working a little different for the user (they get redirected to a site in mobile Safari where they can enter the missing email). If you already have the email address of your customer in the first place, you should avoid setting it to nil, that makes the checkout process more fluent. (By checkout process I mean the interaction that happens once you call `finishWithCompletionBlock:...` on a `TRSOrder` object.)

**Comment by jonasman** [comment] 2017-01-19 10:28
Sorry.

Our pod is 0.6.3
Could that be the difference?

Sent from my iPhone

On 19 Jan 2017, at 12:02, Gero Herkenrath <notifications@github.com<mailto:notifications@github.com>> wrote:


I can't reproduce these warnings, neither in the Example project of the pod nor in a completely fresh test project. I don't see any conflicting nullability specifiers in the header files either. By looking at it, I mean.

Is it possible a pod update somehow messed up your project? Please note that as of 0.8.0 nullability specifiers changed, since now the email is optional when processing an order. I have no idea why you would see any conflicts in the TRSProductReview.h file though, as that wasn't directly affected by this change.

If you still see the warning even in a test project that uses the 0.8.0 version of the pod please let me know. Maybe you could then share an example project where that happens.

Should it be an issue with the pod itself I apologize for any inconvenience. You can be assured that these warnings should not lead to problems in your app as long as you are using the affected methods according to the documentation. A missing email simply results in the checkout process working a little different for the user (they get redirected to a site in mobile Safari where they can enter the missing email). If you already have the email address of your customer in the first place, you should avoid setting it to nil, that makes the checkout process more fluent. (By checkout process I mean the interaction that happens once you call finishWithCompletionBlock:... on a TRSOrder object.)

-

**Comment by GeroHerkenrath** [comment] 2017-01-19 11:29
As long as it is a clean 0.6.3 it shouldn't, actually... (assuming you don't try to set the email property to `nil` as that was only implemented in 0.8.0)
Weird. Can you try to update the pod to 0.8.0? That should not affect your application in any way, as the updates are backwards compatible (I follow semantic versioning).

**Comment by jonasman** [comment] 2017-01-19 11:33
The complain is with the init of these classes that is ovveriden. And i see that code in the latest master too.

Because in objc the init is nonnull while these 3 classes are nullable.

Sent from my iPhone

On 19 Jan 2017, at 13:29, Gero Herkenrath <notifications@github.com<mailto:notifications@github.com>> wrote:


As long as it is a clean 0.6.3 it shouldn't, actually... (assuming you don't try to set the email property to nil as that was only implemented in 0.8.0)
Weird. Can you try to update the pod to 0.8.0? That should not affect your application in any way, as the updates are backwards compatible (I follow semantic versioning).

-

**Comment by GeroHerkenrath** [comment] 2017-01-19 16:14
Oh, you mean the `init` that is marked as unavailable!

That's still very weird. `init` actually does _not_ really have _any_ nullability specifiers, but indeed the documentation says that callers can assume that it is not nil. However, any nullability specifiers should  be able to be overridden anyways. Of course I do not provide an implementation (since the method is unavailable), so I guess the compiler checks against the superclass, which is `NSObject` in this case. I checked the header files, but as expected there's no nullability specifier. And I use the latest Xcode as well (i.e. the 10.2 SDK). For me there are simply no warnings, and neither syntactically nor conceptually there should be anything wrong with the mentioned headers. :(

Could you provide me with a sample project that demonstrates the issue? I can only assume that maybe some clang flags are set in your project to enforce some stricter check, as in my fresh test project I don't get any warnings (and neither does the travis build system, btw).

I'd like to eventually fix this, I can simply define that method as `nonnull` (it's not used anyways after all), but I'd also prefer to understand the issue completely first. 

If you're willing to go the extra mile for me, perhaps you can also check whether maybe my Objective-C header files are for some weird reason out of date: Just go to the definition of the `init` method (select the method in e.g. `TRSOrder.h`, right click, chose "Jump to Definition", then chose `-[NSObject init]`. Is the `init` in your header actually defined as `nonnull`? That would be a pretty big surprise to me, as in my header it isn't.

**Comment by jonasman** [comment] 2017-01-20 11:22
objc init
![screen shot 2017-01-20 at 13 19 34](https://cloud.githubusercontent.com/assets/1762910/22147832/555a3900-df13-11e6-9dc5-fa2f9534496c.png)

your init:
![screen shot 2017-01-20 at 13 21 35](https://cloud.githubusercontent.com/assets/1762910/22147841/676cea70-df13-11e6-8837-e159ce414014.png)


the override changes the declaration with the "nullable" keyword. Which is why Xcode complains.
My xcode is 8.2.1 (latest)

**Comment by GeroHerkenrath** [comment] 2017-01-20 12:55
I am using the same Xcode and apparently the same SDK version (besides I doubt that `NSObject.h` changed in the last few versions). 

I don't get these warnings, neither in the actual Example project that's part of the pod nor in a new test project that uses the pod.
Changing, i.e. overriding, a nullability specifier should actually be fine in a subclass, otherwise no subclass could ever have a simple `init` that is nullable at all. I assume it's a combination of there being no actual implementation for this `init`, it being marked as unavailable (i.e. the `__attribute__((unavailable(...`), and some compiler flags in your specific project. As said, a brand new project using the pod throws no warnings and without a demo project that demonstrates this I can't reproduce this behavior.

I will close this issue for now, but on the next release of the SDK I will try to circumvent this. If you can't show me a demo project I can use to check this against, would you be willing to test a branch of the pod before I release? That way I could ensure the next version does indeed not throw warnings for you, otherwise I would have to basically guess a fix.

**Comment by GeroHerkenrath** [comment] 2017-01-20 15:00
Update:
After googling for similar errors I finally found the reason for those warnings: It's the bridging mechanism when using a swift project. No offense, but it would have helped me had you just told me your application was written in swift or uses swift.
I will fix this in a next release. Issue opened until that's done.

**Comment by jonasman** [comment] 2017-01-20 15:04
Hm sorry . Yes our project is swift!

**Comment by GeroHerkenrath** [comment] 2017-01-20 15:24
No problem. :) I will fix the issue and publish a new version of the pod on Monday. Obviously that won't affect the version you currently use, but 0.8.1 will then no longer throw warnings when used in a swift project. Since there are no breaking changes you can simply update if those warnings annoy you (technically you would be fine, but I know from experience how those little yellow triangles bug me when compiling... 😁 )

**Closed as completed** 2017-01-23 10:24 UTC

**Comment by GeroHerkenrath** [comment] 2017-01-23 10:44
This is now live in version 0.8.1 of the pod. Swift projects should no longer give those 3 warnings. I'd recommend updating your project, as besides this fix, the displayed trustcard now looks a lot nicer. :)
