### ISSUE TITLE
Nil value for TRSProductReview.creationDate causes EXC_BAD_INSTRUCTION

### ISSUE THREAD

**Issue by JethroLR** [trustedshops/trustbadge_iOS#55] opened 2018-08-14 10:11 UTC
Hi there 
We are using your SDK to display product reviews in our app. It appears as though on some occasions, a `TRSProductReview` object contains a nil value for `creationDate`. Because creationDate is marked as nonnull, it cannot return a nil value. This means that in the event that the date is nil, when we try read the date (whether to convert it to a String or even check if it's nil), our app throws an exception.

Do you have any suggestions as to how we can prevent this crash or are there any changes you can make?

**Comment by GeroHerkenrath** [comment] 2018-08-27 08:13
Hello Jethro,

sorry for replying a bit late, I was on vacation and my colleagues had too much to do to dig into this. This is definitely not intended, i.e. a bug. I assume the problem might be with an API change on our part, but it's really weird `creationDate` becomes nil; this should be caught before the initializer is actually called, iirc.

To track this down properly it would help me to get some further information from you:

- Is your project written in swift? (The bridging to Objective-C can swallow or produce some warnings, I want to ensure I can reproduce the issue and this will help me to do so.)
- Can you provide me with an example product SKU that results in corrupted reviews on loading? I'd also need your TSID to look that up in our database to check how the date gets mangled. If you don't want to provide that publicly here, just email me the info to gero.herkenrath@trustedshops.de

I'm afraid I can't come up with a temporary workaround for this off the top of my head, as you probably have no way to safely unwrap the date object without causing the crash. I will try to publish a bugfix asap. Sorry again for the inconvenience!

**Comment by GeroHerkenrath** [comment] 2019-08-27 06:19
Hm, seeing as I was never able to reproduce it (and then admittedly forgot about it) I assume this is no longer relevant, so I'll close this.

@JethroLR, if this pops up again let me know and I will reopen.

**Closed as completed by GeroHerkenrath** 2019-08-27 06:19 UTC
